/* test_golden.c — the golden images (design.md §7.7, §15.2 M4).
 *
 * Fixed windows, decoded and drawn by the firmware's own ula.c, compared
 * with the PPMs in test/host/golden/. Every scene's character sets are
 * the public-domain fallback font and a mosaic set worked out here, so
 * the images hold nothing of the ROMs (§18 item 1) and CI runs them.
 *
 *   test_golden            compare; on a mismatch, write <name>.actual.ppm
 *                          into the working directory for inspection
 *   test_golden --write D  write every image into D instead
 *   test_golden --frames D write every scene's frame into D as
 *                          <name>.frame: the 10 KiB window, then the mode
 *                          byte and the blink byte, for the reference
 *                          renderer (tools/render-diff.sh, §13.4)
 *
 * The images are generated by the code they check, so a golden proves
 * nothing until someone has looked at it (EL §5.7), and nothing beyond
 * our own opinion until the reference has drawn the same frame. Look
 * before committing one.
 */

#include <stdlib.h>
#include <string.h>

#include "bus.h"
#include "font.h"
#include "oric.h"
#include "test_util.h"
#include "ula.h"

#define PPM_HEADER "P6\n240 224\n255\n"
#define PPM_BYTES  (ORIC_PIXEL_W * ORIC_PIXEL_H * 3u)

static oric_frame_t g_f;
static ula_cell_t   g_cells[ORIC_PIXEL_H][ORIC_SCREEN_COLS];
static uint8_t      g_got[PPM_BYTES];
static uint8_t      g_want[PPM_BYTES];
static oric_t       g_m;

static uint8_t *at(uint16_t addr) { return &g_f.window[addr - ORIC_VIDEO_BASE]; }
static uint8_t *text(unsigned row, unsigned col) {
    return at((uint16_t)(ORIC_TEXT_BASE + row * ORIC_SCREEN_COLS + col));
}
static uint8_t *hires(unsigned line) {
    return at((uint16_t)(ORIC_HIRES_BASE + line * ORIC_SCREEN_COLS));
}

static void put(unsigned row, unsigned col, const char *s, uint8_t flip) {
    for (; *s && col < ORIC_SCREEN_COLS; s++) *text(row, col++) = (uint8_t)(*s ^ flip);
}

/* A 2x3 mosaic from a code's low six bits, as a teletext set draws one:
 * bit 0 top left, bit 1 top right, down to bit 5 bottom right. Our own
 * pattern for the alternate set, so its cells are told apart at a look. */
static void mosaic(uint8_t *set) {
    for (unsigned code = 0; code < 128u; code++)
        for (unsigned r = 0; r < 8u; r++) {
            unsigned band = r < 3u ? 0u : r < 6u ? 1u : 2u;
            uint8_t row = 0;
            if (code & (1u << (band * 2u))) row |= 0x38u;
            if (code & (2u << (band * 2u))) row |= 0x07u;
            set[code * 8u + r] = (r == 2u || r == 5u) ? 0 : row;
        }
}

/* Spaces in text mode at 50 Hz, the fallback font as the standard set in
 * both modes, the mosaic as the alternate, and an empty bitmap. */
static void blank(void) {
    memset(g_f.window, 0, sizeof g_f.window);
    font_fallback_charset(at(ORIC_CHARSET_TEXT));
    font_fallback_charset(at(ORIC_CHARSET_HIRES));
    mosaic(at(ORIC_CHARSET_TEXT + ORIC_CHARSET_BYTES));
    mosaic(at(ORIC_CHARSET_HIRES + ORIC_CHARSET_BYTES));
    for (unsigned r = 0; r < ORIC_SCREEN_ROWS; r++)
        for (unsigned c = 0; c < ORIC_SCREEN_COLS; c++) *text(r, c) = ' ';
    g_f.mode = ULA_MODE_50HZ;
    g_f.blink_on = true;
}

/* ---- the scenes ------------------------------------------------------ */

/* Each colour as ink on each as paper: row 4 + 2i has ink i, and its
 * eight blocks of five cells each a paper. */
static void scene_colours(void) {
    blank();
    put(1, 1, "INK ON PAPER, 0-7 EACH", 0);
    for (unsigned i = 0; i < 8u; i++) {
        unsigned row = 4u + 2u * i;
        for (unsigned p = 0; p < 8u; p++) {
            unsigned c = p * 5u;
            *text(row, c) = (uint8_t)(0x10u | p);
            *text(row, c + 1u) = (uint8_t)i;
            *text(row, c + 2u) = 'A';
            *text(row, c + 3u) = 'b';
            *text(row, c + 4u) = (uint8_t)('0' + i);
        }
    }
}

/* Bit 7 inverts: text, inverse text, and attribute cells with and
 * without it, which show their paper and its inverse (§16). */
static void scene_inverse(void) {
    blank();
    put(2, 2, "Normal text, 0123", 0);
    put(4, 2, "Inverse text, 0123", 0x80u);
    *text(6, 0) = 0x14;
    put(6, 1, "blue paper", 0);
    *text(6, 12) = 0x94;            /* paper blue, inverted: a yellow cell */
    put(6, 13, "after #94", 0);
    *text(6, 23) = 0x81;            /* ink red, inverted: blue ^ 7 */
    put(6, 24, "after #81", 0x80u);
    for (unsigned c = 0; c < ORIC_SCREEN_COLS; c++) *text(8, c) = ' ' | 0x80u;
    for (unsigned c = 0; c < 20u; c++) *text(10, c * 2u) = (uint8_t)(0x90u | (c & 7u));
}

/* Both character sets: the standard set's 96 glyphs on rows 2-4, the
 * alternate's (#09) on rows 7-9, its inverse on rows 12-14. */
static void scene_charsets(void) {
    blank();
    for (unsigned k = 0; k < 96u; k++) {
        unsigned row = k / 32u, col = 4u + k % 32u;
        *text(2u + row, col) = (uint8_t)(0x20u + k);
        *text(7u + row, col) = (uint8_t)(0x20u + k);
        *text(12u + row, col) = (uint8_t)(0xA0u + k);
    }
    for (unsigned r = 7; r < 15u; r++) *text(r, 2) = 0x09;
    put(17, 2, "#08 STANDARD, #09 ALTERNATE", 0);
}

/* Double height on an even row and the odd row below it (the whole
 * glyph), then on an odd row alone (bottom halves) and an even row
 * alone (top halves) (§16). */
static void scene_double(void) {
    blank();
    for (unsigned r = 4; r <= 5u; r++) {
        *text(r, 1) = 0x0A;
        put(r, 2, "DOUBLE height, rows 4-5", 0);
    }
    *text(9, 1) = 0x0A;
    put(9, 2, "odd row alone: bottoms", 0);
    *text(12, 1) = 0x0A;
    put(12, 2, "even row alone: tops", 0);
    for (unsigned r = 16; r <= 17u; r++) {
        *text(r, 0) = 0x03;
        *text(r, 1) = 0x0B;           /* double height in the alternate set */
        put(r, 2, "ABCDEFGHIJKLMNOP", 0);
        *text(r, 20) = 0x0E;          /* double and blinking */
        put(r, 21, "BLINK", 0x80u);
    }
}

/* Blink (#0C), shown and hidden: plain, inverse, in colour, and an
 * attribute that ends it. */
static void scene_blink(bool on) {
    blank();
    g_f.blink_on = on;
    *text(3, 1) = 0x0C;
    put(3, 2, "blinking", 0);
    *text(3, 11) = 0x08;
    put(3, 12, "steady", 0);
    *text(5, 1) = 0x0C;
    put(5, 2, "inverse blink", 0x80u);
    *text(7, 0) = 0x16;
    *text(7, 1) = 0x01;
    *text(7, 2) = 0x0C;
    put(7, 3, "red on cyan, blinking", 0);
}
static void scene_blink_on(void) { scene_blink(true); }
static void scene_blink_off(void) { scene_blink(false); }

/* A drawing for the bitmap: a circle and diagonals, so a misplaced line
 * or a swapped pixel shows. */
static void draw_bitmap(unsigned from, unsigned to) {
    for (unsigned y = from; y < to; y++) {
        uint8_t *l = hires(y);
        for (unsigned x = 0; x < ORIC_SCREEN_COLS; x++) l[x] = 0x40;
        for (unsigned px = 0; px < ORIC_PIXEL_W; px++) {
            int dx = (int)px - 120, dy = (int)y - 100;
            int d2 = dx * dx + dy * dy;
            bool on = (d2 > 70 * 70 && d2 < 76 * 76) || px == y || px == 239u - y ||
                      (px / 6u == 39u && y % 4u == 0);
            if (on) l[px / 6u] |= (uint8_t)(0x20u >> (px % 6u));
        }
    }
}

/* Hires from the field's start: the drawing, colour attributes at the
 * start of some lines, an inverse band, and the text window below in
 * the hires character set (§2.2, §16). */
static void scene_hires(void) {
    blank();
    g_f.mode = ULA_MODE_HIRES | ULA_MODE_50HZ;
    draw_bitmap(0, ORIC_HIRES_LINES);
    for (unsigned y = 20; y < 180u; y++) {
        hires(y)[0] = (uint8_t)(0x10u | ((y / 20u) & 7u));   /* paper */
        hires(y)[1] = (uint8_t)((y / 10u) & 7u);              /* ink   */
    }
    for (unsigned y = 90; y < 110u; y++)
        for (unsigned x = 30; x < 38u; x++) hires(y)[x] |= 0x80u;
    put(25, 1, "HIRES TEXT WINDOW, ROW 25", 0);
    *text(26, 1) = 0x09;
    put(26, 2, "alternate set: ABCDEFGH", 0);
    put(27, 1, "row 27", 0x80u);
}

/* Text above a mode attribute at row 10, col 20 (#1E: hires, 50 Hz),
 * which moves the rest of line 80, and every line after, to the
 * bitmap (§7.4, §16). The text window is the hires one. The drawing
 * stops at line 128, where the bitmap's addresses reach the text mode's
 * character sets (#B400) and, from line 176, the text screen (#BB80):
 * below it those bytes show as pixels, as an Oric's would. */
static void scene_mode_split(void) {
    blank();
    for (unsigned r = 0; r < 10u; r++) put(r, 1, "text mode, before the attribute", 0);
    /* Row 10 is drawn on line 80 alone: the lines after it start in
     * hires. Inverse spaces make that one line solid up to col 19. */
    for (unsigned c = 0; c < 20u; c++) *text(10, c) = ' ' | 0x80u;
    draw_bitmap(80, 128);
    *text(10, 20) = 0x1E;
    put(25, 1, "text window, hires character set", 0);
}

/* What the 16K mirror hands the presenter: scene_colours, written to a
 * 16K machine at #1800-#3FFF and taken with oric_video_take. It must
 * draw the same picture as the 48K one, so its golden is that one. */
static void scene_mirror16k(void) {
    scene_colours();
    oric_config_t cfg;
    oric_config_default(&cfg);
    cfg.ram = ORIC_RAM_16K;
    oric_init(&g_m, &cfg);
    for (unsigned i = 0; i < ORIC_VIDEO_BYTES; i++)
        bus_write(&g_m, (uint16_t)((ORIC_VIDEO_BASE + i) & 0x3FFFu), g_f.window[i]);
    memset(&g_f, 0, sizeof g_f);
    oric_video_take(&g_m, &g_f);
}

typedef struct {
    const char *name, *golden;
    void (*fill)(void);
} scene_t;

static const scene_t scenes[] = {
    { "colours",    "colours",    scene_colours },
    { "inverse",    "inverse",    scene_inverse },
    { "charsets",   "charsets",   scene_charsets },
    { "double",     "double",     scene_double },
    { "blink_on",   "blink_on",   scene_blink_on },
    { "blink_off",  "blink_off",  scene_blink_off },
    { "hires",      "hires",      scene_hires },
    { "mode_split", "mode_split", scene_mode_split },
    { "mirror16k",  "colours",    scene_mirror16k },
};

/* ---- rendering and files --------------------------------------------- */

static void render(uint8_t *ppm) {
    uint16_t row[ORIC_PIXEL_W];
    ula_decode(&g_f, g_cells);
    for (unsigned y = 0; y < ORIC_PIXEL_H; y++) {
        ula_row(g_cells[y], 0, ORIC_SCREEN_COLS - 1u, ula_palette_rgb565, row);
        for (unsigned x = 0; x < ORIC_PIXEL_W; x++) {
            uint16_t v = row[x];
            uint8_t *p = &ppm[(y * ORIC_PIXEL_W + x) * 3u];
            p[0] = (uint8_t)(((v >> 11) & 0x1Fu) * 255u / 31u);
            p[1] = (uint8_t)(((v >> 5) & 0x3Fu) * 255u / 63u);
            p[2] = (uint8_t)((v & 0x1Fu) * 255u / 31u);
        }
    }
}

static bool write_file(const char *path, const void *a, size_t na, const void *b, size_t nb) {
    FILE *f = fopen(path, "wb");
    if (!f) return false;
    bool ok = fwrite(a, 1, na, f) == na && fwrite(b, 1, nb, f) == nb;
    return fclose(f) == 0 && ok;
}

static bool read_ppm(const char *path, uint8_t *out) {
    FILE *f = fopen(path, "rb");
    if (!f) return false;
    char hdr[sizeof PPM_HEADER - 1];
    bool ok = fread(hdr, 1, sizeof hdr, f) == sizeof hdr &&
              memcmp(hdr, PPM_HEADER, sizeof hdr) == 0 && fread(out, 1, PPM_BYTES, f) == PPM_BYTES;
    fclose(f);
    return ok;
}

int main(int argc, char **argv) {
    const char *write_dir = NULL, *frame_dir = NULL;
    if (argc == 3 && !strcmp(argv[1], "--write")) write_dir = argv[2];
    else if (argc == 3 && !strcmp(argv[1], "--frames")) frame_dir = argv[2];
    else if (argc != 1) {
        fprintf(stderr, "usage: %s [--write DIR | --frames DIR]\n", argv[0]);
        return 2;
    }

    char path[1024];
    for (unsigned i = 0; i < sizeof scenes / sizeof scenes[0]; i++) {
        const scene_t *s = &scenes[i];
        s->fill();
        render(g_got);

        if (frame_dir) {
            uint8_t tail[2] = { g_f.mode, g_f.blink_on };
            snprintf(path, sizeof path, "%s/%s.frame", frame_dir, s->name);
            CHECK(write_file(path, g_f.window, sizeof g_f.window, tail, sizeof tail), "write %s",
                  path);
            continue;
        }
        if (write_dir) {
            if (strcmp(s->name, s->golden) != 0) continue;   /* shares another's golden */
            snprintf(path, sizeof path, "%s/%s.ppm", write_dir, s->name);
            CHECK(write_file(path, PPM_HEADER, sizeof PPM_HEADER - 1, g_got, PPM_BYTES),
                  "write %s", path);
            continue;
        }

        snprintf(path, sizeof path, "%s/%s.ppm", PICO_ORIC_GOLDEN_DIR, s->golden);
        if (!read_ppm(path, g_want)) {
            CHECK(0, "%s: cannot read %s", s->name, path);
            continue;
        }
        bool same = memcmp(g_got, g_want, PPM_BYTES) == 0;
        if (!same) {
            snprintf(path, sizeof path, "%s.actual.ppm", s->name);
            write_file(path, PPM_HEADER, sizeof PPM_HEADER - 1, g_got, PPM_BYTES);
        }
        CHECK(same, "%s differs from golden %s.ppm (wrote %s)", s->name, s->golden, path);
    }

    TEST_DONE();
}
