/* font.h — the emulator's own fonts (design.md §7.6).
 *
 * The emulator's pages (menu, About, missing-ROM) are drawn in the Oric's
 * font read from the ROM's table, not from character RAM, so a program
 * that redefines a glyph cannot corrupt them (EL §5.8). With no Oric ROM
 * on the card, the missing-ROM page uses the public-domain fallback.
 *
 * Both are laid out as the ULA reads a character set (§2.5): 128 glyphs
 * of 8 rows, bit 5 the leftmost of six pixels.
 */
#ifndef PICO_ORIC_FONT_H
#define PICO_ORIC_FONT_H

#include <stdbool.h>
#include <stdint.h>

#include "config.h"
#include "romset.h"

/* The printable codes #20-#7F; #00-#1F are attributes, never glyphs. */
#define FONT_FIRST   0x20u
#define FONT_GLYPHS    96u

/* The standard character set as the ROM writes it to #B500-#B7FF at
 * power-on: its 96-glyph table at #FC70 in 1.0 and #FC78 in 1.1, which
 * ends where the key table begins (§16, read 2026-10-08). Codes #00-#1F,
 * which the copy does not write, are zero. test_font holds it to what
 * each ROM writes. False for a ROM that is not BASIC. */
bool font_from_rom(rom_id_t id, const uint8_t *rom, uint8_t out[ORIC_CHARSET_BYTES]);

/* The fallback's 96 glyphs, codes #20-#7F (font_fallback.c, generated by
 * tools/mkfont.py from X.Org's public-domain 5x8). */
extern const uint8_t font_fallback[FONT_GLYPHS * ORIC_GLYPH_H];

/* The fallback as a whole character set, #00-#1F zero. */
void font_fallback_charset(uint8_t out[ORIC_CHARSET_BYTES]);

#endif /* PICO_ORIC_FONT_H */
