#!/usr/bin/env python3
"""Generate src/core/font_fallback.c from X.Org's misc-fixed 5x8 font.

The missing-ROM page needs a font when no Oric ROM is on the card
(design.md §7.6). This is the one font the tree keeps for it: the 5x8
"Fixed" of X.Org's font/misc-misc, which its own COPYRIGHT property puts
in the public domain ("Public domain font.  Share and enjoy."). It is
converted, not redrawn (emulator-lessons.md §5.5: never fabricate one).

    curl -sfL -o 5x8.bdf \\
      https://gitlab.freedesktop.org/xorg/font/misc-misc/-/raw/c4e2af05583764fae3d0b2aa20d5c93b031cbcbf/5x8.bdf
    python3 -I tools/mkfont.py 5x8.bdf > src/core/font_fallback.c

Each glyph's five columns go in bits 5-1 of an Oric glyph row, bit 5
leftmost, leaving bit 0 blank as the Oric's own font does; its eight rows
are placed by the BDF's bounding box against the font's descent. Codes
#20-#7E come from the font; #7F, which ASCII leaves without a glyph, is
blank.
"""

import sys

PINNED = "c4e2af05583764fae3d0b2aa20d5c93b031cbcbf"
FIRST, LAST = 0x20, 0x7F


def parse(path):
    glyphs, ascent, descent, cur = {}, None, None, None
    with open(path, encoding="ascii") as f:
        lines = iter(f.read().splitlines())
    for line in lines:
        word = line.split()
        if not word:
            continue
        if word[0] == "COPYRIGHT":
            if "Public domain" not in line:
                sys.exit("not the public-domain font: " + line)
        elif word[0] == "FONT_ASCENT":
            ascent = int(word[1])
        elif word[0] == "FONT_DESCENT":
            descent = int(word[1])
        elif word[0] == "ENCODING":
            cur = {"code": int(word[1])}
        elif word[0] == "BBX":
            cur["bbx"] = [int(w) for w in word[1:5]]
        elif word[0] == "BITMAP":
            w, h, _, _ = cur["bbx"]
            rows = [int(next(lines), 16) for _ in range(h)]
            cur["rows"] = rows
            glyphs[cur["code"]] = cur
    if ascent is None or descent is None or ascent + descent != 8:
        sys.exit("expected an 8-pixel font")
    return glyphs, ascent


def oric_rows(g, ascent):
    w, h, xoff, yoff = g["bbx"]
    if w + xoff > 5:
        sys.exit("glyph %#x is wider than 5" % g["code"])
    out = [0] * 8
    top = ascent - (yoff + h)          # the bitmap's first row in the cell
    for i, bits in enumerate(g["rows"]):
        y = top + i
        if not 0 <= y < 8:
            sys.exit("glyph %#x leaves the cell" % g["code"])
        # BDF rows are left-aligned in whole bytes: bit 7 is the leftmost.
        out[y] = ((bits >> xoff) >> 2) & 0x3E
    return out


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: mkfont.py 5x8.bdf")
    glyphs, ascent = parse(sys.argv[1])
    print("/* font_fallback.c — generated by tools/mkfont.py; do not edit.")
    print(" *")
    print(" * X.Org's misc-fixed 5x8 (font/misc-misc at %s)," % PINNED[:12])
    print(' * whose COPYRIGHT property reads "Public domain font.  Share and')
    print(' * enjoy." Codes #20-#7F, eight rows each, bit 5 leftmost (THIRD-PARTY.md).')
    print(" */")
    print()
    print('#include "font.h"')
    print()
    print("const uint8_t font_fallback[FONT_GLYPHS * ORIC_GLYPH_H] = {")
    for code in range(FIRST, LAST + 1):
        rows = oric_rows(glyphs[code], ascent) if code in glyphs and code != 0x7F else [0] * 8
        ch = chr(code) if code != 0x7F else "DEL"
        if ch == "\\":
            ch = "backslash"
        print("    %s, /* #%02X %s */" % (", ".join("0x%02X" % r for r in rows), code, ch))
    print("};")


main()
