# version.cmake — writes pico_oric_version.h from `git describe` (design.md
# §4.1, §15.2 M0). Run at build time, not configure time, since a configure-time
# value goes stale at the next commit. The header is rewritten only when
# the text changes, so an unchanged tree does not rebuild what includes it.
#
#   cmake -DSRC=<source dir> -DOUT=<header> -P version.cmake

execute_process(
    COMMAND git describe --always --dirty
    WORKING_DIRECTORY ${SRC}
    OUTPUT_VARIABLE version
    OUTPUT_STRIP_TRAILING_WHITESPACE
    ERROR_QUIET
    RESULT_VARIABLE result
)
if (NOT result EQUAL 0 OR version STREQUAL "")
    set(version "unknown")
endif()

set(text "/* Generated by cmake/version.cmake at build time. */\n#define PICO_ORIC_VERSION \"${version}\"\n")
set(old "")
if (EXISTS ${OUT})
    file(READ ${OUT} old)
endif()
if (NOT old STREQUAL text)
    file(WRITE ${OUT} "${text}")
endif()
